// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class categoryfieldinccs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryfieldinccs));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251541467_category field in ccs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
